### ISSUE TITLE
ImportError: No module named readline on Windows - workaround

### ISSUE THREAD

**Issue by nickolay** [JosuaKrause/quick_server#9]
Apparently the `readline` module can be unavailable on Windows, but thankfully there's [a drop-in replacement](https://stackoverflow.com/a/6024996/1026), which worked for me on Python 2.7 from python.org:

```
$ pip install pyreadline

try:
  import readline
except ImportError:
  import pyreadline as readline
```

**Comment by JosuaKrause** [comment]
fixed by d0f6e46363e76b7b6373901d67e8dadcd06ea847

thanks a lot :)
